Draft: Add overdeliveries to logistics
stockhive-uni/stockhiveapp pull request #32
Opened 2024-12-03 12:17 UTC by ibzm

2024-12-03 21:19 UTC, JacoMH commented
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`stock_hive`.`order_item`, CONSTRAINT `order_item_order_id_foreign` FOREIGN KEY (`order_id`) REFERENCES `order` (`id`) ON DELETE CASCADE) (Connection: mysql, SQL: insert into `order_item` (`item_id`, `order_id`, `ordered`, `price`) values (1, 1, 10, 5.99), (2, 1, 20, 3.49), (3, 2, 5, 12.99), (1, 3, 15, 4.99))

  at vendor\laravel\framework\src\Illuminate\Database\Connection.php:825
    821▕                     $this->getName(), $query, $this->prepareBindings($bindings), $e
    822▕                 );
    823▕             }
    824▕
  ➜ 825▕             throw new QueryException(     
    826▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    827▕             );
    828▕         }
    829▕     }

eign` FOREIGN KEY (`order_id`) REFERENCES `order` (`id`) ON DELETE CASCADE)")

  2   vendor\laravel\framework\src\Illuminate\Database\MySqlConnection.php:53
      PDOStatement::execute()

this error was thrown when attempting to migrate your database

2024-12-03 21:19 UTC, JacoMH requested changes
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`stock_hive`.`order_item`, CONSTRAINT `order_item_order_id_foreign` FOREIGN KEY (`order_id`) REFERENCES `order` (`id`) ON DELETE CASCADE) (Connection: mysql, SQL: insert into `order_item` (`item_id`, `order_id`, `ordered`, `price`) values (1, 1, 10, 5.99), (2, 1, 20, 3.49), (3, 2, 5, 12.99), (1, 3, 15, 4.99))

  at vendor\laravel\framework\src\Illuminate\Database\Connection.php:825
    821▕                     $this->getName(), $query, $this->prepareBindings($bindings), $e
    822▕                 );
    823▕             }
    824▕
  ➜ 825▕             throw new QueryException(     
    826▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    827▕             );
    828▕         }
    829▕     }

eign` FOREIGN KEY (`order_id`) REFERENCES `order` (`id`) ON DELETE CASCADE)")

  2   vendor\laravel\framework\src\Illuminate\Database\MySqlConnection.php:53
      PDOStatement::execute() 

review your database, this error was thrown when attempting to build it on my machine

2024-12-04 11:59 UTC, WebExtension1 requested changes
Other than these small changes, all looks good.

2024-12-04 11:59 UTC, WebExtension1 commented on resources/views/Logistics/index.blade.php
> +                                <x-primary-button>View Order</x-primary-button>
Make this link to Jacobs pre-existing View Order page

2024-12-04 11:59 UTC, WebExtension1 commented on resources/views/Logistics/show.blade.php
>          <p><strong>Store ID:</strong> {{ $order->store_id }}</p>
Remove store id

2024-12-04 11:59 UTC, WebExtension1 commented on resources/views/Logistics/show.blade.php
>          <p><strong>User ID:</strong> {{ $order->user_id }}</p>
Username instead of user id

2024-12-04 14:19 UTC, merged