Jaco mh inventory changes
stockhive-uni/stockhiveapp pull request #38
Opened 2024-12-05 16:29 UTC by JacoMH

-can now add specific amounts to floor

-can now remove specific amounts from floor back to storage

**added an id field in store_item_storage to do this, please rebuild the database on your version**

2024-12-05 16:52 UTC, WebExtension1 requested changes
Incorrect quantities in db. When moving 8/10 items over, 8 should be moved, and 2 should be kept. Instead, 2 are both moved and kept. The expiration date is also not moved across. Ideally you should check to see if that item already exists in that location with that date, but that isn't necessary.

2024-12-05 16:53 UTC, JacoMH commented
expiration date is currently not in use, so i am not putting it in. But the other thing i will take a look at

2024-12-06 16:57 UTC, WebExtension1 approved these changes

2024-12-06 16:57 UTC, WebExtension1 commented
Thoroughly tested moving stock and I can't break it, good job.

2024-12-06 16:57 UTC, merged